#!/usr/bin/env python

import sys
import rospy
from crazyflie_driver.msg import Position
from geometry_msgs.msg import TransformStamped, PoseStamped
from aruco_msgs.msg import MarkerArray
from std_msgs.msg import String

pose = None

def callback(read_pose):
	global pose
	pose = read_pose

def moveCallback(cmd):
		print(type(cmd))
		cmd = cmd.data
		print(type(cmd))
		if cmd == "a" or cmd == 's' or cmd =='d' or cmd == 'w':
			print('ja')
			pos = Position()	
			pos.header.stamp = rospy.Time.now()
			if cmd == 'w':
				print('hej')
				pos.x = pose.pose.position.x
				pos.y = pose.pose.position.y
				pos.yaw = 0
				pos.z = pose.pose.position.z + 0.05

			if cmd == 's':
				pos.x = pose.pose.position.x
				pos.y = pose.pose.position.y
				pos.yaw = 0
				pos.z = pose.pose.position.z - 0.05
			if cmd == 'a':
				pos.x = pose.pose.position.x + 0.05
				pos.y = pose.pose.position.y
				pos.yaw = 0
				pos.z = pose.pose.position.z 
			if cmd == 'd':
				pos.x = pose.pose.position.x
				pos.y = pose.pose.position.y + 0.05
				pos.yaw = 0
				pos.z = pose.pose.position.z
			print(pos)
			
			pub.publish(pos)


		
rospy.init_node('teleop')
rospy.Subscriber('/cf1/pose', PoseStamped, callback)
pub = rospy.Publisher('/cf1/cmd_position', Position, queue_size=2)

move = rospy.Publisher('/movement', String, queue_size = 2)
rospy.Subscriber('/movement', String, moveCallback)

def main():
	print('Control drone with w, a,s and d')
	rate = rospy.Rate(20)
	while not rospy.is_shutdown():
		com = raw_input()
		move.publish(com)


if __name__ == '__main__':
	main()
